# Generated by Django 5.1.7 on 2025-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rssfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
