# Generated by Django 5.1.7 on 2025-04-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX news_search_gin
                ON news_newsarticle
                USING GIN ((
                  setweight(to_tsvector('simple'::regconfig, coalesce("news_newsarticle"."title", '')), 'A') ||
                  setweight(to_tsvector('simple', coalesce("news_newsarticle"."content", '')), 'B')
                ));
                
            """,
            reverse_sql="DROP INDEX news_search_gin;"
        )
    ]
